version: '3.8'
services:
    chatbot:
        image: 'google-generativeai'
        container_name: chatbot
        build:
           context: . 
           dockerfile: Dockerfile
        env_file: .env
        environment:
           GEMINI_API_KEY: '${GEMINI_API_KEY}'
